### ISSUE TITLE
Feedback for “Filecoin”

### ISSUE THREAD

**Issue by rickiey** [Ankr-network/ankr-docs#1110] opened 2023-03-23 07:36 UTC
`Filecoin.MpoolPush` need write permission

**Comment by galleon8** [comment] 2023-03-23 09:54
Hi rickiey. Thanks for your feedback. We're currently addressing this issue in order to have all those Filecoin permissions without requesting them by default. We'll get back to you as soon as it's done.

**Comment by galleon8** [comment] 2023-07-20 10:56
Hey rickiey. Sorry for the late response. We've changed the node settings and it must be working with no need to obtain permissions. Please check if that works for you. Best regards from devs.

**Comment by rickiey** [comment] 2023-08-28 02:44
I ran into this problem again `missing permission to invoke MpoolPush' (need 'write')}`

**Comment by galleon8** [comment] 2023-09-26 15:29
Hi rickiey. We're sorry for your troubles. We checked with the devs and the issue still requires fixing, though we can't allocate resources for that right now — it might take a bit more time than usual for us to fix that. Could you please tell us if you're using our Public or Premium tier? For your troubles, we would like to send bonus API credits into your account, so you can use our Premium service tier for some time when the issue is fixed.

**Comment by raproid** [comment] 2024-02-07 16:48
Is this issue still relevant, or should we close it as "not planned"?

**Comment by raproid** [comment] 2024-02-20 06:02
I'm closing it as "not planned".

**Closed** 2024-02-20 06:02 UTC
